name: helloworld

on:
  push:
    branches: [ master ]
    paths:
      - 'helloworld/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'helloworld/**'

defaults:
  run:
    working-directory: ./helloworld


jobs:

  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout project
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Setup GO
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Say "Hello, World!"
        run: go run .
